spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  sevlet:
    encoding:
      charset: UTF-8
      force: true

logging:
  config: classpath:config/logback-spring.xml
